server:
#  context-path: /chatbot
  port: 8081
  tomcat:
    uri-encoding: utf-8
  session:
    #需要注意单位是秒
    timeout: 120


spring:
  application:
      name: json-service
  session:
      store-type: none
 
 

  messages:
    #设定Message bundles的编码，默认: UTF-8
    encoding: UTF-8
    #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: messages/i18n/i18n
    #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
    cache-seconds: 1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
      enabled: true
 
      
##woody start###
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/sunway?useUnicode=true&characterEncoding=gbk&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong 
    username: root
    password: howay
    maximumPoolSize: 8
    minimumIdle: 2
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 10
    maxActive: 10
    tomcat:
      max-active: 10
      maxActive: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none









